# Python Numpy库使用笔记  
## Numpy特性  
1. numpy采用c语言编写算法库，使用连续内存存储，内置函数运算速度较Python快  
2. import numpy as np为推荐导入方式，不推荐全部导入，避免命名冲突  
3. 可以进行快速矩阵运算，而不需要python循环
4. 提供对硬盘数据进行读写的工具，并对内存映射文件进行操作

## Ndarray多维数组
Numpy的核心对象，**同类（每一个元素是相同类型）**数据容器。
1. 数组shape和dtype属性分别表示数组的维度信息和元素数据类型
```
data.shape
data.dtype
```  
2. 生成Ndarray  
    1. 使用array/asarry函数
    array接受一个序列（如列表，元组等），返回一个数组。类型和维度会自动识别（未指定shape，dtype的情况下）。asaaray在符合shape和dtype的情况下，如果输入为一个ndaary那么不会复制它，直接返回数组本身，而array会产生一个copy。
    2. ones/ones_like, zeros/zeros_like, empty/empty_like, full/full_like, eye, identity函数
    生成某些特殊类型的数组，如ones生成指定形状和数据类型的数组，而ones_like生成所谓数组一样形状的全1数组。   

In [13]:
import numpy as np

arr1 = np.arange(10)
print(arr1.shape, arr1.dtype)
arr2 = np.array(arr1, ndmin=2)
print(arr2)
arr3 = np.zeros((2,3))
arr4 = np.ones_like(arr3)
print(arr3, arr4, sep='\n')
print(np.eye(2,5), np.eye(2,5, k=1), sep='\n')
print(np.identity(3))


(10,) int32
[[0 1 2 3 4 5 6 7 8 9]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


3. ndarray的数据类型dtype  
使用dtype可以查看数组的数据类型，而方法asdtype则可以修改数组的数据类型，当不能转换时会引发ValueError异常，且使用asdtype会生成一个新的数组。dtype可以使用类型np.float32, np.int8等也可以使用类型代码，'i1'代表int8等等。  
4. 数据的算术  
在任何形状相同的数组之间的算术运算，都是逐元素进行的。而标量运算是对每个元素进行运算。  
**在不同形状的数组之间进行运算，要遵循numpy的传播规则，需要特别注意**

In [20]:
arr1 = np.array([[1,2],[3,4]])
print(arr1*arr1, arr1*2, sep= '\n')

[[ 1  4]
 [ 9 16]]
[[2 4]
 [6 8]]


5. 数组的切片和索引  
    1. 基础索引和切片  
    对于1-d数组，索引和切片类似python的列表。但是要注意这种**切片和索引下返回的都是原数组的视图**，即任何修改都会反应在原数组上。对于更高维度的数组，每一个索引代表的不再是一个元素，而是一个降低了维度的数组。切片的规则和索引相同。但是切片所得要注意是获得了一维数组还是获得了某一个维为1的多维数组(可以理解为索引会降维，而切片不会降维)。

In [25]:
arr0 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr0[:,2], arr0[:,2,:2],sep="\n")
arr = np.array([[1,2],[3,4]])
print(arr[1,:].shape, arr[1:,:].shape)

[[7 8 9]]
[[7 8]]
(2,) (1, 2)
