# Python Numpy库使用笔记  
## Numpy特性  
1. numpy采用c语言编写算法库，使用连续内存存储，内置函数运算速度较Python快  
2. import numpy as np为推荐导入方式，不推荐全部导入，避免命名冲突  
3. 可以进行快速矩阵运算，而不需要python循环
4. 提供对硬盘数据进行读写的工具，并对内存映射文件进行操作

## Ndarray多维数组
Numpy的核心对象，**同类（每一个元素是相同类型）**数据容器。
1. 数组shape和dtype属性分别表示数组的维度信息和元素数据类型
```
data.shape
data.dtype
```  
2. 生成Ndarray  
    1. 使用array/asarry函数
    array接受一个序列（如列表，元组等），返回一个数组。类型和维度会自动识别（未指定shape，dtype的情况下）。asaaray在符合shape和dtype的情况下，如果输入为一个ndaary那么不会复制它，直接返回数组本身，而array会产生一个copy。
    2. ones/ones_like, zeros/zeros_like, empty/empty_like, full/full_like, eye, identity函数
    生成某些特殊类型的数组，如ones生成指定形状和数据类型的数组，而ones_like生成所谓数组一样形状的全1数组。   

In [3]:
import numpy as np

arr1 = np.arange(10)
print(arr1.shape, arr1.dtype)
arr2 = np.array(arr1, ndmin=2)
print(arr2)
arr3 = np.zeros((2,3))
arr4 = np.ones_like(arr3)
print(arr3, arr4, sep='\n')
print(np.eye(2,5), np.eye(2,5, k=1), sep='\n')
print(np.identity(3))


(10,) int32
[[0 1 2 3 4 5 6 7 8 9]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


3. ndarray的数据类型dtype  
使用dtype可以查看数组的数据类型，而方法asdtype则可以修改数组的数据类型，当不能转换时会引发ValueError异常，且使用asdtype会生成一个新的数组。dtype可以使用类型np.float32, np.int8等也可以使用类型代码，'i1'代表int8等等。  
4. 数据的算术  
在任何形状相同的数组之间的算术运算，都是逐元素进行的。而标量运算是对每个元素进行运算。  
**在不同形状的数组之间进行运算，要遵循numpy的传播规则，需要特别注意**

In [20]:
arr1 = np.array([[1,2],[3,4]])
print(arr1*arr1, arr1*2, sep= '\n')

[[ 1  4]
 [ 9 16]]
[[2 4]
 [6 8]]


5. 数组的切片和索引  
    1. 基础索引和切片  
    对于1-d数组，索引和切片类似python的列表。但是要注意这种**切片和索引下返回的都是原数组的视图**，即任何修改都会反应在原数组上。对于更高维度的数组，每一个索引代表的不再是一个元素，而是一个降低了维度的数组。切片的规则和索引相同。但是切片所得要注意是获得了一维数组还是获得了某一个维为1的多维数组(可以理解为索引会降维，而切片不会降维)。
    2. 布尔索引  
    使用比较运算符== != > < 等会产生布尔数组，并且支持&和|逻辑运算（不支持and ， or），而且使用布尔索引时数组长度不正确会引发异常.使用布尔索引返回的数组是原数组的拷贝。
        1. 1-d数组使用布尔索引  
        此时的索引必须是一维布尔数组，返回一维数组，元素取值为根据布尔数组中取值为True的元素选取原数组相应位置的元素。  
        2. n-d数组使用布尔索引  
        此时的索引可以使一维布尔数组或者多维布尔数组，一维布尔数组的长度必须跟被索引数组的0-轴长度一致；多维布尔数组形状必须跟被索引数组形状一致。此时一维布尔数组索引获得的是多维数组的0-轴组成的数组，而多维布尔数组索引获得的是取值为True的位置对应的原数组的元素组成一维数组。  
    3. 数组/列表索引  
    此时的索引，返回的均为数据拷贝。
        1. 1-d数组，1个索引  
        此时，根据索引值依次从数组取出数据，构成跟索引形式一样的数组。（此时索引为数组或者整数列表的结果是一样的。）  
        2. 1-d数组，多个索引  
        此时，当索引为列表时，会引发IndexError异常；当索引为数组时，根据索引值从原始数据中取出数值，构成新的数组（具有跟索引数组相同的形状）。  
        3. n-d数组，1个索引（数组）  
        此时，根据索引值依次从数组的0轴取出数据，构成跟索引形式一样的数组（相当于用原数组的行替代了索引值）。  
        4. n-d数组，多个索引（数组）  
        此时，要求多个索引数组具有相同的形状。根据多个索引数组组成的索引对，从原数组取出数组，构成跟索引数组形状一致的新数组。

In [5]:
#基础索引和切片
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr0 = np.arange(5)

#基础索引和切片，返回原数组的切片视图
print(arr, arr[:,2], arr[0:2,:1], arr[2,2], arr[0], sep = "\n**********\n")
print("*"*30)

#布尔索引,生成新的数组
print(arr0, arr0[[True,False,False,True,False]], arr0[np.array([True,False,False,True,True])], sep='\n**********\n')
tmp = arr > 5
print("*"*30)
print(arr, arr[[True,False,True]], arr[np.array(tmp)], sep='\n**********\n')
print("*"*30)

#数组/列表索引，生成新的数组
#1-d数组
print(arr0, arr0[[1,3,2]], arr0[np.array([1,4,2])],arr0[np.array([[1,0],[2,4],[3,3]])] , sep='\n**********\n')
print("*"*30)
#n-d数组
print(arr, arr[[1,0]], arr[np.array([2,0])], sep='\n**********\n')
print("*"*30)
print(arr, arr[[1,2,0],[0,0,2]], arr[np.array([[1,1],[2,2]])], sep='\n**********\n')
print("*"*30)
print(arr, arr[np.array([[1,0],[1,2]]),np.array([[0,1],[1,2]])], sep='\n**********\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
**********
[3 6 9]
**********
[[1]
 [4]]
**********
9
**********
[1 2 3]
******************************
[0 1 2 3 4]
**********
[0 3]
**********
[0 3 4]
******************************
[[1 2 3]
 [4 5 6]
 [7 8 9]]
**********
[[1 2 3]
 [7 8 9]]
**********
[6 7 8 9]
******************************
[0 1 2 3 4]
**********
[1 3 2]
**********
[1 4 2]
**********
[[1 0]
 [2 4]
 [3 3]]
******************************
[[1 2 3]
 [4 5 6]
 [7 8 9]]
**********
[[4 5 6]
 [1 2 3]]
**********
[[7 8 9]
 [1 2 3]]
******************************
[[1 2 3]
 [4 5 6]
 [7 8 9]]
**********
[4 7 3]
**********
[[[4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]]]
******************************
[[1 2 3]
 [4 5 6]
 [7 8 9]]
**********
[[4 2]
 [5 9]]


6. 数组的转置和换轴  
数组具有方法transpose和swapaxes，均可完成数组的转置等功能，同时np.transpose和np.swapaxes也是相同额功能。而且数组的T属性，代表了数组的转置。需要注意的是**所有转置获得的是原数组的视图，任何修改会反应在原数组上。**  
    1. T属性  
    代表了最特殊的一种换轴，即矩阵的转置。  
    2. transpose方法  
    这里使用np.transpose来讲解，如果不带任何数轴的参数，默认结果为矩阵转置。当含有数组的列表时，进行换轴操作。以三维数组为例，索引数据时采用一个三元组来查找，例如a[0,1,0]代表查找0轴，1行，0列的数据。如果进行np.transpose(a, [1,0,2])那么，本来在a[0,1,0]的数据会被放置在a[1,0,0]位置上，即可以理解为换轴换的是索引的数组序列，正常情况下数轴顺序是[0,1,2]，那么顺序[1,0,2]代表了0轴和1轴的索引顺序交换。  
    3. swapaxes方法  
    理解了transpose方法，就不难理解swapaxes方法，他只是简化版的换轴方法，仅交换两个数轴。  

In [21]:
narr = np.arange(6).reshape(2,3)
print(narr, narr.T, np.transpose(narr), np.swapaxes(narr,1,0), sep='\n*********\n')
print("*"*30)
narr = np.arange(24).reshape(2,3,4)
print(narr, narr.T, narr.transpose(2,1,0), np.transpose(narr, [1,0,2]), np.swapaxes(narr, 1, 0), sep='\n*********\n')

[[0 1 2]
 [3 4 5]]
*********
[[0 3]
 [1 4]
 [2 5]]
*********
[[0 3]
 [1 4]
 [2 5]]
*********
[[0 3]
 [1 4]
 [2 5]]
******************************
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
*********
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
*********
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
*********
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
*********
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


7. 常用逐元素的函数  
逐元素意思就是对每个元素应用函数，通常分为一元和二元函数：  
    1. 一元函数  
    通常有sqrt（相同于arr\**0.5), square(相当于arr\**2），abs，fabs，sign（计算每个元素的符号，正数1，负数-1，零0），log等对数，exp，三角函数等，isnan，rint，modf等等。具体含义可以查看相关说明。  
    2.二元函数  
    subract，multiply（同符号*），power，maximum，minimum，比较操作符，逻辑操作符（& | ^）。

In [26]:
a = np.arange(5).reshape(5,1)
b = np.arange(5).reshape(1,5)
print(a*b,b*a, np.dot(b,a), np.power(a,b.T), sep='\n')

[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]
[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]
[[30]]
[[  1]
 [  1]
 [  4]
 [ 27]
 [256]]
